### ISSUE TITLE
More info about whats going on under the hood

### ISSUE THREAD

**Issue by alirdn** [Snipa22/xmr-node-proxy#67]
Hi

I'm trying to rewrite XNP in a more modular way, so adding a feature, fix bugs etc. becomes easier for contributors. But, the code is not documented, lots of unnecessary code, and even wrong variables naming in some places. (I think XNP is part of a closed source project that @Snipa22 removed some parts and released it as XNP. You can just see the list of dependencies, that includes 17 module that more than 50% is not needed at all. Or lib/support.js file that exported 7 functions, but only 1 is needed). So a hard time to figure out whats going on under the hood. Especially the codes in lib/xmr.js, and functions like handleNewBlockTemplate, balanceWorkers etc. that works with the hashes, blocks and mining stuff.

So could you @Snipa22 help me by giving information about the mechanisms that XNP uses, How XNP generate target according to diff, And why the only pool that supported is nodejs-pool (I thinks it's about the agent part that will sent to pool when creating pool socket connection).

I will release my work as an open source project (Maybe as a PR), so the community could get the most benefit if I could rewrite it. 

Finally, a big thanks to @Snipa22 for his works.

**Comment by Snipa22** [comment]
1.  The core of XNP comes from NodeJS-pool, which is why you see that there's extra code laying around.  Most of this was left for one reason or another, the most common one being, that I planned on using it later (sendEmail being the easy option), which should all be obvious enough if you look at how I wrote NodeJS-pool

2.  NodeJS-Pool is the only pool supported, as XNP uses the extended stratum impl I wrote into NodeJS-pool, nothing is keeping anyone from implementing this into Node-CN pool, and it's fairly obvious where and how I wrote it in.

3. XNP doesn't care about generating a special target based on the diff, it generates the target by shoving the data to cnUtils, which does the conversion from a raw BT to a hashable, then tells the miner separately, what it's required diff is: https://github.com/Snipa22/xmr-node-proxy/blob/master/lib/xmr.js#L70

Honestly, if you can't decode this project by following the standard workflows that are in it, I would strongly advise against editing or attempting to modify it.  These are all pretty standard flows for cryptos, and overall, are pretty easy to grasp and modify.  There's very little non-used code (As I've stripped most of it out), and there's not really anything "hard" here to grasp under the hood, past knowledge of how pools and crypto mining works.
