### ISSUE TITLE
Setting password via miner

### ISSUE THREAD

**Issue by onesvat** [Snipa22/xmr-node-proxy#69]
Hello,

Is it possible that set different passwords for miners so I can check stats from poll by individual miner?

I can see only default password for all miners connected.

**Comment by passnet** [comment]
That is not possible by design. The proxy has to login to the pool to get the job with nonce. If you log to the pool with different password you will get a different job, thus making proxy acting only as a network proxy.
If you need stats - enable debugging by setting DEBUG=* env variable. Check #33 for more.

**Comment by onesvat** [comment]
Thank you for your answer. It is working with your proxy.diff.js and glidaya's repository.

Can we say that we can't trust these numbers because xmr-node-proxy does not check the shares for validation?

**Comment by passnet** [comment]
It does checks for share validity. It only does other checks first, like if it's diff are higher than pool diff and just drops it if it's invalid there. So hash/s proxy counts are pretty reliable for measuring speed. But your pool will still "see" a lower hash/s than your combined proxy hashes/s because some low diff shares found which might be valid for particular miner are invalid for pool so they are dropped.

**Comment by Snipa22** [comment]
Not quite, the proxy checks validity only in the case of HashDiff > PoolRequestedDiff, otherwise, it performs no validation.  This does mean that it's perfectly possible someone could slam your proxy with a massive number of low-diff shares, but it wouldn't do anything, as they wouldn't be submitted to the pool, but would throw off your h/s count.

**Comment by onesvat** [comment]
Thank you. I understand. If miner send random hashes with right difficulty, then XNP cannot detect it is valid or not.

**Comment by Snipa22** [comment]
Correct, XNP will not validate the share unless it's > the point at which the pool's diff wants it to be.  This is why it can't be blindly trusted to handle payouts/etc.
